# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48bedd31e69f5c0aa9c49ae1639f5f1f83f4f77bb9ffcf8d43fcb853e167f84f4f92d85fe6760244b73736f8ed3cab39dd15177c7c62ae602894e6865ebd0545

test:
  secret_key_base: 6a9f63303074491518c1b86246d6326fe90a5a57919efa00c1795e5352bd12c59c3b6988a65f03386e089e32b10eb4e39681ea0c09701d9b299970ac8547bcd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
